import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/styles/globals.css'
import NavBar from '@/components/NavBar/NavBar'
import localfont from 'next/font/local'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const darkblow = localfont({
  src:[
    {
      path: "../../../public/fonts/Darkblow.otf",
      
      weight:"500"
    }
  ],
  variable:"--font-darkblow"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${darkblow.variable} ${inter.className}`}>
        <NavBar / >
        {children}
        <Footer/>
        </body>
    </html>
  )
}
